defaults: &defaults
  working_directory: ~/cypress-sample-project
  docker:
    - image: circleci/node:latest

version: 2.1

jobs:
  cypress:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Installing packages
          command: npm install

      - run:
          name: Installing dependencies
          command: |
            sudo apt update
            sudo apt-get install cmake xvfb libgbm-dev libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth

      - run:
          name: Starting frontend server
          command: npm run start
          background: true

      - run:
          name: Running cypress tests
          command: npm run cy:run

      - store_artifacts:
          name: Saving Cypress screenshots
          path: ~/cypress-sample-project/cypress/screenshots
          destination: /cypress-screenshots

workflows:
  version: 2.1
  build:
    jobs:
      - cypress
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master
    jobs:
      - cypress
