name: Run Cypress Tests in Edge

on:
  push:
  schedule:
    - cron: '0 3 * * *'

jobs:
  tests:
    runs-on: windows-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress info
        uses: ./
        with:
          build: npm run info
          working-directory: examples/chrome
          browser: edge

      - name: Cypress run Edge
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          config-file: cypress.json
          wait-on: "http://localhost:3000"
          wait-on-timeout: 1
          browser: edge
          headless: true

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots-in-edge
          path: app/edge/cypress/screenshots

      - uses: actions/upload-artifact@v2
        with:
          name: video-in-edge
          path: app/edge/cypress/videos

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: app/edge
