name: Run Cypress Tests in Firefox

on:
  push:
  schedule:
    - cron: '0 3 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run Firefox
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          config-file: cypress.json
          wait-on: "http://localhost:3000"
          wait-on-timeout: 1
          browser: firefox

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots-in-firefox
          path: app/firefox/cypress/screenshots

      - uses: actions/upload-artifact@v2
        with:
          name: video-in-firefox
          path: app/firefox/cypress/videos

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: app/firefox
