name: Run Cypress Tests

on: push

jobs:
  cypress-run:
    name: Run Cypress
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          config-file: cypress.json
          wait-on: "http://localhost:3000"
          wait-on-timeout: 300
          browser: chrome
          headless: true
